--CAU1
select NHANVIEN.HONV,TENLOT , TENNV, LUONG
from NHANVIEN join PHONGBAN ON NHANVIEN.PHONG=PHONGBAN.MAPHG
WHERE NHANVIEN.LUONG> (SELECT AVG(NHANVIEN.LUONG) FROM NHANVIEN WHERE PHONGBAN.MAPHG='5')
--cau2
select NHANVIEN.HONV,TENLOT,TENNV
FROM NHANVIEN
where NHANVIEN.MANV NOT IN (SELECT THANNHAN.MA_NVIEN  FROM THANNHAN)
 --CAU3
 SELECT NHANVIEN.HONV , TENLOT, TENNV
 FROM NHANVIEN join PHONGBAN ON NHANVIEN.MANV=PHONGBAN.TRUONGPHG
 WHERE EXISTS(SELECT THANNHAN.MA_NVIEN FROM THANNHAN WHERE NHANVIEN.MANV=THANNHAN.MA_NVIEN)
 --CAU4
 SELECT *
 FROM DEAN 
 WHERE DEAN.MADA NOT IN (SELECT PHANCONG.MADA FROM PHANCONG JOIN NHANVIEN ON PHANCONG.MA_NVIEN=NHANVIEN.MANV WHERE PHANCONG.MA_NVIEN=009)
 --CAU5
 SELECT PHONGBAN.MAPHG, PHONGBAN.TENPHG,TENNV
 FROM PHONGBAN JOIN NHANVIEN ON PHONGBAN.TRUONGPHG=NHANVIEN.MANV
 AND PHONGBAN.MAPHG IN(SELECT PHONG
                        FROM NHANVIEN
						GROUP BY PHONG
						HAVING COUNT(NHANVIEN.MANV)=(SELECT MAX(SL)
						       FROM (SELECT COUNT(NHANVIEN.MANV) AS SL FROM NHANVIEN
							   GROUP BY PHONG) as BangSL))